global class AccessControlWrapper {
    public String barcode;
    public Long ticketId;
    public String ticketState;
    public String cancellationCause;
    public String tariffCode;
    public Long productId;
    public String productCode;
    public String validityStartTime;
    public String culturalContactNumber;
    public Map<String, Object> holderInfo;
    public String validityEndTime;
    public String salesChannelCodeMapping;
    public Long orderId;
    public String creationDate;
    public Integer groupSize;
    public Decimal price;
}
